name: select

on:
    push:
        branches: [master]

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: docker build -t scope .
            - run: docker images
            - run: docker run --rm scope
