name: off

on:
    push:
        branches: [master]

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: docker build -t aa .        

    play:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pip install requests
            - run: python chels.py

# 2ой сопособ написания (Последовательный)

    build-run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: docker build -t aas .
            - run: docker run --rm aas
            


